# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_buildMatrixD <- function(ts, as, bs, zs) {
    .Call('iHaz_cpp_buildMatrixD', PACKAGE = 'iHaz', ts, as, bs, zs)
}

cpp_logLikeRestricted <- function(lambda, dsZ, dZ) {
    .Call('iHaz_cpp_logLikeRestricted', PACKAGE = 'iHaz', lambda, dsZ, dZ)
}

cpp_nablaLogLikeRestrict <- function(lambda, dsZ, dZ) {
    .Call('iHaz_cpp_nablaLogLikeRestrict', PACKAGE = 'iHaz', lambda, dsZ, dZ)
}

cpp_newLambda <- function(pI, lambda, dsZ, dZ) {
    .Call('iHaz_cpp_newLambda', PACKAGE = 'iHaz', pI, lambda, dsZ, dZ)
}

cpp_solve <- function(ys, xs) {
    .Call('iHaz_cpp_solve', PACKAGE = 'iHaz', ys, xs)
}

cpp_findLocalMax <- function(x, tol) {
    .Call('iHaz_cpp_findLocalMax', PACKAGE = 'iHaz', x, tol)
}

cpp_scale <- function(matrix, vec) {
    .Call('iHaz_cpp_scale', PACKAGE = 'iHaz', matrix, vec)
}

fast_factor <- function(x) {
    .Call('iHaz_fast_factor', PACKAGE = 'iHaz', x)
}

myf <- function(X) {
    .Call('iHaz_myf', PACKAGE = 'iHaz', X)
}

